### ISSUE TITLE
Support viewing problemset submissions

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#267] opened 2020-03-02 12:27 UTC
As a problem author, I want to view the submissions of the problemset I authored in [Problems](https://tlx.toki.id/problems)

One suggestion is to add "Author" role

<img width="251" alt="Screenshot 2020-03-02 at 8 25 04 PM" src="https://user-images.githubusercontent.com/18303489/75676368-070f2580-5cc4-11ea-9871-90c3c7e076e4.png">
<img width="303" alt="Screenshot 2020-03-02 at 8 25 24 PM" src="https://user-images.githubusercontent.com/18303489/75676381-0bd3d980-5cc4-11ea-9647-3188ab39ae70.png">

**Comment by fushar** [comment] 2020-10-02 08:06
Marking this as duplicate of https://github.com/ia-toki/judgels/issues/321.

The above issue should solve this problem.

**Closed as completed by fushar** 2020-10-02 08:06 UTC
Labels: duplicate
