### ISSUE TITLE
[feature-request] download or copy solution in submission

### ISSUE THREAD

**Issue by freethought101** [ia-toki/judgels#287] opened 2020-06-06 13:53 UTC
simple yet helpful feature to learners. we can see our solution, but when we copy it manually, it always add extra enter on every line. it seems trivial, but on a little longer code this can be hassle. e.g:

source:
int main(){
      return 0;
}
copy:

int main(){

      return 0;

}

**Comment by fushar** [comment] 2020-10-02 07:15
I cannot reproduce it. Which browser are you using? Can you describe exact steps to reproduce this bug?

**Comment by prabowo02** [comment] 2020-10-02 08:08
I was experiencing the same thing, where an extra line is added in between every line of code. But it seems the problem is no longer there for now.

**Comment by fushar** [comment] 2020-10-02 08:11
Cool, closing it then. Feel free to reopen if this occurs again.

**Closed as completed by fushar** 2020-10-02 08:11 UTC
Labels: invalid
